"""Paper-derived inner-solver primitive for Lemma 5.1 / Eq. (5.7).

After introducing ``xi = sqrt(X)`` and

    W_n = (phi_n, U_n, K_n, Pi_n, d_xi phi_n, d_xi U_n)^T,

Section 5 rewrites the positive-order coefficient equations as

    d_xi W_n + xi^-1 diag(0,0,2,0,3,1) W_n
        = A0 W_n + A1 d_eta W_n + f_n,       (5.7)
    W_n(0, eta) = 0.

The paper inverts the singular diagonal part componentwise with

    (G g)_i(xi) = integral_0^xi (s/xi)^c_i g_i(s) ds,
    c = (0,0,2,0,3,1),

and solves the equation by the Picard series generated by
``K = G (A0 + A1 d_eta)``.

This module implements exactly that radial inverse and one Picard-map
application.  ``A0``, ``A1`` and ``f_n`` are deliberately explicit caller
inputs: until Issue #1 supplies the paper's materialized leading profile, the
repository cannot instantiate the coefficient matrices from the manuscript.
Consequently this is solver infrastructure / formal structure, not a
paper-exact positive-order background coefficient.
"""
from __future__ import annotations

from numbers import Integral
from typing import Callable, Sequence
import math

import numpy as np

from .quadrature import integrate

Vector6 = np.ndarray
VectorField6 = Callable[[float, float], Sequence[float]]
MatrixField6 = Callable[[float, float], Sequence[Sequence[float]]]

EQ_5_7_SINGULAR_WEIGHTS = (0, 0, 2, 0, 3, 1)


def _xi(value: float) -> float:
    value = float(value)
    if not math.isfinite(value) or value < 0.0:
        raise ValueError("xi must be finite and nonnegative")
    return value


def _eta(value: float) -> float:
    value = float(value)
    if not math.isfinite(value) or abs(value) > 1.0:
        raise ValueError("eta must be finite with |eta| <= 1")
    return value


def _positive_order(n: int) -> int:
    if isinstance(n, bool) or not isinstance(n, Integral) or n < 1:
        raise ValueError("coefficient order n must be a positive integer")
    return int(n)


def _vector6(value: Sequence[float], name: str) -> Vector6:
    out = np.asarray(value, dtype=float)
    if out.shape != (6,) or not np.all(np.isfinite(out)):
        raise ValueError(f"{name} must be a finite vector of shape (6,)")
    return out


def _matrix6(value: Sequence[Sequence[float]], name: str) -> np.ndarray:
    out = np.asarray(value, dtype=float)
    if out.shape != (6, 6) or not np.all(np.isfinite(out)):
        raise ValueError(f"{name} must be a finite matrix of shape (6, 6)")
    return out


def singular_inverse_eq_5_7(
    xi: float,
    eta: float,
    source: VectorField6,
    *,
    quadrature_points: int = 32,
) -> Vector6:
    """Apply the manuscript's singular radial inverse ``G`` in Eq. (5.7).

    The formula is evaluated directly, so no division by ``xi`` occurs at the
    axis.  The returned value is exactly zero at ``xi=0``, as required by
    Lemma 5.1.  For ``xi>0`` each component is integrated independently using
    the repository's cached Gauss-Legendre quadrature; the quadrature itself is
    numerical and is not promoted to a formal certificate.
    """

    xi, eta = _xi(xi), _eta(eta)
    if not callable(source):
        raise TypeError("source must be callable")
    if xi == 0.0:
        return np.zeros(6)

    # Validate the vector-valued source at one endpoint before launching six
    # scalar quadratures.  Every quadrature evaluation is validated as well.
    _vector6(source(0.0, eta), "source")
    answer = np.empty(6)
    for component, weight in enumerate(EQ_5_7_SINGULAR_WEIGHTS):
        answer[component] = integrate(
            lambda s, component=component, weight=weight: float(
                (s / xi) ** weight
                * _vector6(source(s, eta), "source")[component]
            ),
            0.0,
            xi,
            n=quadrature_points,
        )
    if not np.all(np.isfinite(answer)):
        raise OverflowError("Eq. (5.7) singular inverse produced nonfinite output")
    return answer


def picard_map_eq_5_7(
    n: int,
    xi: float,
    eta: float,
    previous: VectorField6,
    previous_eta_derivative: VectorField6,
    A0: MatrixField6,
    A1: MatrixField6,
    lower_order_source: VectorField6,
    *,
    quadrature_points: int = 32,
) -> Vector6:
    """Apply one exact-structure Picard map for the order-``n`` Eq. (5.7).

    Given a previous iterate ``W``, this returns

        G [ A0 W + A1 d_eta W + f_n ].

    This is the iteration used in the proof of Lemma 5.1.  It is *not* a claim
    that caller-supplied matrices are the paper's ``A0``/``A1``.  In
    particular, callers must not label the result paper-exact unless those
    matrices and ``f_n`` have independently been derived from the materialized
    Section-4 leading profile and finalized lower orders.
    """

    _positive_order(n)
    xi, eta = _xi(xi), _eta(eta)
    for fn, name in (
        (previous, "previous"),
        (previous_eta_derivative, "previous_eta_derivative"),
        (A0, "A0"),
        (A1, "A1"),
        (lower_order_source, "lower_order_source"),
    ):
        if not callable(fn):
            raise TypeError(f"{name} must be callable")

    def rhs(s: float, eta_value: float) -> Vector6:
        W = _vector6(previous(s, eta_value), "previous")
        d_eta_W = _vector6(
            previous_eta_derivative(s, eta_value), "previous_eta_derivative"
        )
        matrix0 = _matrix6(A0(s, eta_value), "A0")
        matrix1 = _matrix6(A1(s, eta_value), "A1")
        forcing = _vector6(lower_order_source(s, eta_value), "lower_order_source")
        value = matrix0 @ W + matrix1 @ d_eta_W + forcing
        if not np.all(np.isfinite(value)):
            raise OverflowError("Eq. (5.7) Picard right-hand side is nonfinite")
        return value

    return singular_inverse_eq_5_7(
        xi, eta, rhs, quadrature_points=quadrature_points
    )


def first_picard_term_eq_5_7(
    n: int,
    xi: float,
    eta: float,
    lower_order_source: VectorField6,
    *,
    quadrature_points: int = 32,
) -> Vector6:
    """Return the genuine first term ``G f_n`` of the Lemma-5.1 Picard series.

    For each positive order the paper writes

        W_n = sum_{k>=0} K^k G f_n.

    This routine evaluates only the ``k=0`` term.  It is useful for a verifiable
    positive-order solver step while the profile-dependent matrices remain
    blocked upstream; it is not the converged order-``n`` coefficient.
    """

    _positive_order(n)
    return singular_inverse_eq_5_7(
        xi, eta, lower_order_source, quadrature_points=quadrature_points
    )
