"""Exact clean-room replay of one Kokuno Section 8 mean-correction identity.

This module independently implements the public MC14 solenoidal axial
realization identity.  It deliberately works only with exact scalar jets; it
does not materialize the compactly supported mean correction, imported pulse
inverse, or any all-stage construction.
"""
from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from numbers import Integral


def _exact(value: object, name: str) -> Fraction:
    if isinstance(value, bool):
        raise TypeError(f"{name} must be an int or Fraction, not bool")
    if isinstance(value, Fraction):
        return value
    if isinstance(value, Integral):
        return Fraction(int(value), 1)
    raise TypeError(
        f"{name} must be an int or Fraction; float/Decimal approximations are rejected"
    )


@dataclass(frozen=True)
class MeanSolenoidalJet:
    """Exact local jet for the MC14 correction generated by ``Psi_*``.

    The public formula is

    ``Delta beta = -epsilon * d_Z Psi_*``
    ``Delta gamma = (D_r + 1/R) Psi_*``.

    The cylindrical divergence contribution is
    ``(D_r + 1/R) Delta beta + epsilon * d_Z Delta gamma``.
    """

    radius: Fraction | int
    epsilon: Fraction | int
    psi: Fraction | int
    d_r_psi: Fraction | int
    d_z_psi: Fraction | int
    d_rz_psi: Fraction | int

    def __post_init__(self) -> None:
        radius = _exact(self.radius, "radius")
        epsilon = _exact(self.epsilon, "epsilon")
        if radius <= 0:
            raise ValueError("radius must be strictly positive")
        if epsilon <= 0:
            raise ValueError("epsilon must be strictly positive")
        object.__setattr__(self, "radius", radius)
        object.__setattr__(self, "epsilon", epsilon)
        object.__setattr__(self, "psi", _exact(self.psi, "psi"))
        object.__setattr__(self, "d_r_psi", _exact(self.d_r_psi, "d_r_psi"))
        object.__setattr__(self, "d_z_psi", _exact(self.d_z_psi, "d_z_psi"))
        object.__setattr__(self, "d_rz_psi", _exact(self.d_rz_psi, "d_rz_psi"))

    @property
    def delta_beta(self) -> Fraction:
        return -self.epsilon * self.d_z_psi

    @property
    def delta_gamma(self) -> Fraction:
        return self.d_r_psi + self.psi / self.radius

    @property
    def d_r_delta_beta(self) -> Fraction:
        return -self.epsilon * self.d_rz_psi

    @property
    def d_z_delta_gamma(self) -> Fraction:
        return self.d_rz_psi + self.d_z_psi / self.radius

    @property
    def cylindrical_divergence(self) -> Fraction:
        return (
            self.d_r_delta_beta
            + self.delta_beta / self.radius
            + self.epsilon * self.d_z_delta_gamma
        )

    def divergence_with_beta_sign(self, sign: int | Fraction) -> Fraction:
        """Replay the divergence after replacing the required minus sign.

        ``sign=-1`` is the source formula.  This helper exists only to make the
        sign sensitivity explicit in tests; it does not define an alternate
        admissible correction.
        """
        sign_f = _exact(sign, "sign")
        if sign_f not in (Fraction(-1), Fraction(1)):
            raise ValueError("sign must be exactly -1 or 1")
        delta_beta = sign_f * self.epsilon * self.d_z_psi
        d_r_delta_beta = sign_f * self.epsilon * self.d_rz_psi
        return (
            d_r_delta_beta
            + delta_beta / self.radius
            + self.epsilon * self.d_z_delta_gamma
        )

    @property
    def identity_holds_exactly(self) -> bool:
        return self.cylindrical_divergence == 0

    @property
    def status(self) -> str:
        return "formula-level-replay"

    @property
    def actual_compact_correction_field_materialized(self) -> bool:
        return False

    @property
    def actual_wave_defect_consumed(self) -> bool:
        return False

    @property
    def all_stage_convergence_certified(self) -> bool:
        return False

    @property
    def paper_exact_velocity_available(self) -> bool:
        return False

    @property
    def full_reconstruction(self) -> bool:
        return False
